version: '3.9'
services:
  db:
    env_file:
      - .env
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
  www:
    depends_on:
    - db
    image: php:7.4.30-apache
    volumes:
    - "./data/:/var/www/html"
    ports:
    - 80:80
    - 443:443